[custom]
ruleset=☁️ CloudflareTunnel,https://raw.githubusercontent.com/karllee830/Subconverter_Rules/refs/heads/main/Rules/cloudflaretunnel.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/karllee830/Subconverter_Rules/refs/heads/main/Rules/DirectDownload.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🤖 AI服务,https://raw.githubusercontent.com/karllee830/Subconverter_Rules/refs/heads/main/Rules/LLM.list
ruleset=🦀 Claude,https://raw.githubusercontent.com/karllee830/Subconverter_Rules/refs/heads/main/Rules/Claude.list
ruleset=🚨 特殊访问,https://raw.githubusercontent.com/karllee830/Subconverter_Rules/refs/heads/main/Rules/Custom/CustomProxy.list
ruleset=🚨 特殊访问,https://raw.githubusercontent.com/karllee830/Subconverter_Rules/refs/heads/main/Rules/TikTok.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
;ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]DIRECT`[]♻️ 自动测速`.*
custom_proxy_group=♻️ 自动测速`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🤖 AI服务`select`[]🚀 节点选择`[]DIRECT`.*
custom_proxy_group=🦀 Claude`select`[]🚀 节点选择`[]DIRECT`.*
custom_proxy_group=🚨 特殊访问`select`[]🚀 节点选择`[]DIRECT`.*
custom_proxy_group=☁️ CloudflareTunnel`select`[]🚀 节点选择`[]DIRECT`.*
custom_proxy_group=⛔ 应用拦截`select`[]REJECT`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT

add_emoji=true
emoji=(流量|Traffic),📊
emoji=(过期|时间|Expire),⏳
emoji=(🇨🇳|台湾|TW|Taiwan),🇨🇳
emoji=(🇩🇪|德国|DE|Germany),🇩🇪
emoji=(🇬🇧|英国|伦敦|UK|Britain),🇬🇧
emoji=(🇭🇰|香港|深港|HK|Hong Kong),🇭🇰
emoji=(🇯🇵|日本|大阪|东京|JP|Japan),🇯🇵
emoji=(🇷🇺|俄罗斯|RU|Russia),🇷🇺
emoji=(🇸🇬|新加坡|狮城|SG|Singapore),🇸🇬
emoji=(🇰🇷|韩国|KR),🇰🇷
emoji=(🇺🇸|美国|洛杉矶|US|United States),🇺🇸
emoji=(🇹🇷|土耳其|TR|Turkey),🇹🇷
emoji=(🇮🇳|印度|IN|India),🇮🇳
emoji=(🇧🇷|巴西|BR),🇧🇷
emoji=(🇦🇷|阿根廷|AR|Argentina),🇦🇷
emoji=(🇫🇷|法国|FR),🇫🇷
emoji=(🇮🇪|爱尔兰|IE),🇮🇪
emoji=(🇨🇦|加拿大|CA),🇨🇦
emoji=(🇹🇭|泰国|TH),🇹🇭
emoji=(🇻🇳|越南|VN),🇻🇳
emoji=(🇳🇱|荷兰|NL),🇳🇱
emoji=(🇮🇩|印尼|ID),🇮🇩
emoji=(🇿🇦|南非|ZA),🇿🇦
emoji=(🇪🇬|埃及|EG),🇪🇬
emoji=(🇵🇭|菲律宾|PH),🇵🇭
emoji=(🇮🇹|意大利|IT),🇮🇹
emoji=(🇪🇸|西班牙|ES),🇪🇸
emoji=(🇭🇺|匈牙利|HU),🇭🇺
emoji=(🇮🇱|以色列|IL),🇮🇱
emoji=(🇺🇦|乌克兰|UA),🇺🇦
emoji=(🇲🇾|马来西亚|MY),🇲🇾
emoji=(🇵🇰|巴基斯坦|PK),🇵🇰
emoji=(🇲🇩|摩尔多瓦|MD),🇲🇩
emoji=(🇳🇬|尼日利亚|NG),🇳🇬
emoji=(🇦🇺|澳大利亚|悉尼|AU),🇦🇺
emoji=(🇦🇪|迪拜|阿联酋|AE),🇦🇪
emoji=(🇵🇱|波兰|PL),🇵🇱
emoji=(🇱🇺|卢森堡|LU|Luxembourg),🇱🇺
emoji=(📱|CMCC|CT|TG|电信|移动|联通),📱

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
